import os
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from app.config.settings import settings
from app.core.logging import logger


def generate_pdf_report(
    scan_id: int,
    scan_type: str,
    target: str,
    risk_score: int,
    confidence: int,
    explanation: str,
    recommendations: str,
    threat_indicators: list[dict],
) -> str:
    """
    Generates a PDF report and returns the file path.
    """
    logger.info(f"Generating PDF report for Scan ID: {scan_id}")

    os.makedirs(settings.REPORT_DIRECTORY, exist_ok=True)
    file_name = f"report_scan_{scan_id}.pdf"
    file_path = os.path.join(settings.REPORT_DIRECTORY, file_name)

    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter

    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(50, height - 50, "ScamShield AI - Threat Analysis Report")

    # Meta data
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 90, f"Scan ID: {scan_id}")
    c.drawString(
        50,
        height - 110,
        f"Timestamp: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
    )
    c.drawString(50, height - 130, f"Scan Type: {scan_type.upper()}")
    c.drawString(50, height - 150, f"Input Target: {target}")
    c.drawString(
        50, height - 170, f"Generated By: ScamShield AI (Version {settings.VERSION})"
    )

    # Results
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 210, "Analysis Results")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 230, f"Risk Score: {risk_score}/100")
    c.drawString(50, height - 250, f"Confidence: {confidence}%")

    # Indicators
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 290, "Threat Indicators")

    y_pos = height - 310
    c.setFont("Helvetica", 12)
    if not threat_indicators:
        c.drawString(50, y_pos, "None detected.")
        y_pos -= 20
    else:
        for ind in threat_indicators:
            c.drawString(
                50,
                y_pos,
                f"- [{ind.get('severity', 'LOW').upper()}] {ind.get('indicator')}",
            )
            y_pos -= 20

    # Explanations
    y_pos -= 20
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos, "AI Explanation")
    y_pos -= 20

    c.setFont("Helvetica", 11)
    # Basic text wrap simulation
    words = explanation.split()
    line = ""
    for word in words:
        if len(line) + len(word) > 80:
            c.drawString(50, y_pos, line)
            y_pos -= 15
            line = word + " "
        else:
            line += word + " "
    if line:
        c.drawString(50, y_pos, line)
        y_pos -= 30

    # Recommendations
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos, "Recommendations")
    y_pos -= 20

    c.setFont("Helvetica", 11)
    words = recommendations.split()
    line = ""
    for word in words:
        if len(line) + len(word) > 80:
            c.drawString(50, y_pos, line)
            y_pos -= 15
            line = word + " "
        else:
            line += word + " "
    if line:
        c.drawString(50, y_pos, line)

    c.save()
    logger.info(f"PDF report saved at: {file_path}")
    return file_path
