"""Add missing columns

Revision ID: 2b9459c5788f
Revises: 39cb58a19746
Create Date: 2026-07-20 21:12:38.397694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9459c5788f'
down_revision: Union[str, Sequence[str], None] = '39cb58a19746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apk_libraries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_mitre_tactics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('tactic', sa.String(), nullable=False),
    sa.Column('technique', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_yara_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('strings_matched', sa.String(), nullable=True),
    sa.Column('offset', sa.String(), nullable=True),
    sa.Column('rule_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('apk_certificates', sa.Column('trust_level', sa.String(), nullable=True))
    op.add_column('apk_certificates', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('architecture', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('dex_count', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('sha256', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('manifest_json', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('permission_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('certificate_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('manifest_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('component_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('yara_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('network_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('code_risk', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('similarity_score', sa.Integer(), nullable=True))
    op.add_column('apk_scans', sa.Column('closest_sample_id', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('ai_family', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('ai_behaviour', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('ai_impact', sa.String(), nullable=True))
    op.add_column('apk_scans', sa.Column('ai_actions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apk_scans', 'ai_actions')
    op.drop_column('apk_scans', 'ai_impact')
    op.drop_column('apk_scans', 'ai_behaviour')
    op.drop_column('apk_scans', 'ai_family')
    op.drop_column('apk_scans', 'closest_sample_id')
    op.drop_column('apk_scans', 'similarity_score')
    op.drop_column('apk_scans', 'code_risk')
    op.drop_column('apk_scans', 'network_risk')
    op.drop_column('apk_scans', 'yara_risk')
    op.drop_column('apk_scans', 'component_risk')
    op.drop_column('apk_scans', 'manifest_risk')
    op.drop_column('apk_scans', 'certificate_risk')
    op.drop_column('apk_scans', 'permission_risk')
    op.drop_column('apk_scans', 'manifest_json')
    op.drop_column('apk_scans', 'sha256')
    op.drop_column('apk_scans', 'dex_count')
    op.drop_column('apk_scans', 'architecture')
    op.drop_column('apk_scans', 'size_bytes')
    op.drop_column('apk_certificates', 'risk_level')
    op.drop_column('apk_certificates', 'trust_level')
    op.drop_table('apk_yara_matches')
    op.drop_table('apk_mitre_tactics')
    op.drop_table('apk_libraries')
    # ### end Alembic commands ###
