"""Add APK models

Revision ID: 39cb58a19746
Revises: ab4351214ceb
Create Date: 2026-07-19 22:52:04.986985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39cb58a19746'
down_revision: Union[str, Sequence[str], None] = 'ab4351214ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apk_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('version_code', sa.Integer(), nullable=True),
    sa.Column('min_sdk', sa.Integer(), nullable=True),
    sa.Column('target_sdk', sa.Integer(), nullable=True),
    sa.Column('compile_sdk', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('malware_family', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_certificates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('signature_algorithm', sa.String(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('self_signed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_iocs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('protection_level', sa.String(), nullable=True),
    sa.Column('dangerous', sa.Boolean(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apk_permissions')
    op.drop_table('apk_iocs')
    op.drop_table('apk_components')
    op.drop_table('apk_certificates')
    op.drop_table('apk_scans')
    # ### end Alembic commands ###
