"""Add cache tracking to ProviderHealth

Revision ID: 708fa9842d9f
Revises: c8dc29e95c8f
Create Date: 2026-07-17 19:46:50.803198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708fa9842d9f'
down_revision: Union[str, Sequence[str], None] = 'c8dc29e95c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_health', sa.Column('cache_hits', sa.Integer(), nullable=True))
    op.add_column('provider_health', sa.Column('cache_misses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_health', 'cache_misses')
    op.drop_column('provider_health', 'cache_hits')
    # ### end Alembic commands ###
