"""Add ThreatCache and ProviderHealth models

Revision ID: 76aff0f42f9f
Revises: 6d89ab7c797c
Create Date: 2026-07-17 19:21:21.113171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76aff0f42f9f'
down_revision: Union[str, Sequence[str], None] = '6d89ab7c797c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_health',
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('provider_name')
    )
    op.create_index(op.f('ix_provider_health_provider_name'), 'provider_health', ['provider_name'], unique=False)
    op.create_table('threat_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('normalized_input', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_threat_cache_cache_key'), 'threat_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_threat_cache_expires_at'), 'threat_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_threat_cache_normalized_input'), 'threat_cache', ['normalized_input'], unique=False)
    op.create_index(op.f('ix_threat_cache_provider'), 'threat_cache', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_cache_provider'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_normalized_input'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_expires_at'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_cache_key'), table_name='threat_cache')
    op.drop_table('threat_cache')
    op.drop_index(op.f('ix_provider_health_provider_name'), table_name='provider_health')
    op.drop_table('provider_health')
    # ### end Alembic commands ###
