"""clean_init

Revision ID: a8b6936c511c
Revises: 
Create Date: 2026-07-22 02:00:04.517172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b6936c511c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_health',
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('average_latency_ms', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('last_success', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_hits', sa.Integer(), nullable=True),
    sa.Column('cache_misses', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('provider_name')
    )
    op.create_index(op.f('ix_provider_health_provider_name'), 'provider_health', ['provider_name'], unique=False)
    op.create_table('threat_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('normalized_input', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('normalized_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_threat_cache_cache_key'), 'threat_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_threat_cache_expires_at'), 'threat_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_threat_cache_normalized_input'), 'threat_cache', ['normalized_input'], unique=False)
    op.create_index(op.f('ix_threat_cache_provider'), 'threat_cache', ['provider'], unique=False)
    op.create_table('threat_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence_category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_indicators_id'), 'threat_indicators', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('apk_scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('package_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('version_code', sa.Integer(), nullable=True),
    sa.Column('min_sdk', sa.Integer(), nullable=True),
    sa.Column('target_sdk', sa.Integer(), nullable=True),
    sa.Column('compile_sdk', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('dex_count', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('manifest_json', sa.String(), nullable=True),
    sa.Column('permission_risk', sa.Integer(), nullable=True),
    sa.Column('certificate_risk', sa.Integer(), nullable=True),
    sa.Column('manifest_risk', sa.Integer(), nullable=True),
    sa.Column('component_risk', sa.Integer(), nullable=True),
    sa.Column('yara_risk', sa.Integer(), nullable=True),
    sa.Column('network_risk', sa.Integer(), nullable=True),
    sa.Column('code_risk', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('similarity_score', sa.Integer(), nullable=True),
    sa.Column('closest_sample_id', sa.String(), nullable=True),
    sa.Column('ai_family', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('ai_behaviour', sa.String(), nullable=True),
    sa.Column('ai_impact', sa.String(), nullable=True),
    sa.Column('ai_actions', sa.String(), nullable=True),
    sa.Column('malware_family', sa.String(), nullable=True),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('reply_to', sa.String(), nullable=True),
    sa.Column('return_path', sa.String(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('spf_status', sa.String(), nullable=True),
    sa.Column('dkim_status', sa.String(), nullable=True),
    sa.Column('dmarc_status', sa.String(), nullable=True),
    sa.Column('sender_reputation', sa.String(), nullable=True),
    sa.Column('domain_age', sa.Integer(), nullable=True),
    sa.Column('is_disposable', sa.Boolean(), nullable=True),
    sa.Column('is_scam_domain', sa.Boolean(), nullable=True),
    sa.Column('brand_impersonation_target', sa.String(), nullable=True),
    sa.Column('social_engineering_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scans_id'), 'email_scans', ['id'], unique=False)
    op.create_table('message_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('receiver', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('scam_type', sa.String(), nullable=True),
    sa.Column('social_engineering_score', sa.Integer(), nullable=True),
    sa.Column('ocr_confidence', sa.Integer(), nullable=True),
    sa.Column('threat_intel_confidence', sa.Integer(), nullable=True),
    sa.Column('language_confidence', sa.Integer(), nullable=True),
    sa.Column('reputation_confidence', sa.Integer(), nullable=True),
    sa.Column('rule_engine_confidence', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_scans_id'), 'message_scans', ['id'], unique=False)
    op.create_index(op.f('ix_message_scans_platform'), 'message_scans', ['platform'], unique=False)
    op.create_table('qr_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extracted_data', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ai_explanation', sa.String(), nullable=True),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_scans_id'), 'qr_scans', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_table('upi_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('upi_id', sa.String(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ai_explanation', sa.String(), nullable=True),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upi_scans_id'), 'upi_scans', ['id'], unique=False)
    op.create_table('website_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ai_explanation', sa.String(), nullable=True),
    sa.Column('recommendations', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_scans_id'), 'website_scans', ['id'], unique=False)
    op.create_table('apk_certificates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('issuer', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('signature_algorithm', sa.String(), nullable=True),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('self_signed', sa.Boolean(), nullable=True),
    sa.Column('trust_level', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_iocs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('ioc_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_libraries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('risk', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_mitre_tactics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('tactic', sa.String(), nullable=False),
    sa.Column('technique', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_permissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('protection_level', sa.String(), nullable=True),
    sa.Column('dangerous', sa.Boolean(), nullable=True),
    sa.Column('justification', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apk_yara_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('strings_matched', sa.String(), nullable=True),
    sa.Column('offset', sa.String(), nullable=True),
    sa.Column('rule_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['apk_scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('dangerous_extension', sa.Boolean(), nullable=True),
    sa.Column('double_extension', sa.Boolean(), nullable=True),
    sa.Column('is_executable', sa.Boolean(), nullable=True),
    sa.Column('has_macro', sa.Boolean(), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=True),
    sa.Column('is_password_protected', sa.Boolean(), nullable=True),
    sa.Column('vt_detection_ratio', sa.String(), nullable=True),
    sa.Column('vt_first_seen', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_id'), 'email_attachments', ['id'], unique=False)
    op.create_table('email_hops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_hops_id'), 'email_hops', ['id'], unique=False)
    op.create_table('email_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('final_redirect', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('threat_category', sa.String(), nullable=True),
    sa.Column('vt_verdict', sa.String(), nullable=True),
    sa.Column('gsb_verdict', sa.String(), nullable=True),
    sa.Column('urlscan_verdict', sa.String(), nullable=True),
    sa.Column('ssl_status', sa.String(), nullable=True),
    sa.Column('domain_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_urls_id'), 'email_urls', ['id'], unique=False)
    op.create_table('message_iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('ioc_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['message_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_iocs_id'), 'message_iocs', ['id'], unique=False)
    op.create_table('message_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('reputation', sa.String(), nullable=True),
    sa.Column('scam_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['message_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_phones_id'), 'message_phones', ['id'], unique=False)
    op.create_table('message_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('redirect_chain', sa.JSON(), nullable=True),
    sa.Column('provider_results', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['message_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_urls_id'), 'message_urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_urls_id'), table_name='message_urls')
    op.drop_table('message_urls')
    op.drop_index(op.f('ix_message_phones_id'), table_name='message_phones')
    op.drop_table('message_phones')
    op.drop_index(op.f('ix_message_iocs_id'), table_name='message_iocs')
    op.drop_table('message_iocs')
    op.drop_index(op.f('ix_email_urls_id'), table_name='email_urls')
    op.drop_table('email_urls')
    op.drop_index(op.f('ix_email_hops_id'), table_name='email_hops')
    op.drop_table('email_hops')
    op.drop_index(op.f('ix_email_attachments_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_table('apk_yara_matches')
    op.drop_table('apk_permissions')
    op.drop_table('apk_mitre_tactics')
    op.drop_table('apk_libraries')
    op.drop_table('apk_iocs')
    op.drop_table('apk_components')
    op.drop_table('apk_certificates')
    op.drop_index(op.f('ix_website_scans_id'), table_name='website_scans')
    op.drop_table('website_scans')
    op.drop_index(op.f('ix_upi_scans_id'), table_name='upi_scans')
    op.drop_table('upi_scans')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_qr_scans_id'), table_name='qr_scans')
    op.drop_table('qr_scans')
    op.drop_index(op.f('ix_message_scans_platform'), table_name='message_scans')
    op.drop_index(op.f('ix_message_scans_id'), table_name='message_scans')
    op.drop_table('message_scans')
    op.drop_index(op.f('ix_email_scans_id'), table_name='email_scans')
    op.drop_table('email_scans')
    op.drop_table('apk_scans')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threat_indicators_id'), table_name='threat_indicators')
    op.drop_table('threat_indicators')
    op.drop_index(op.f('ix_threat_cache_provider'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_normalized_input'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_expires_at'), table_name='threat_cache')
    op.drop_index(op.f('ix_threat_cache_cache_key'), table_name='threat_cache')
    op.drop_table('threat_cache')
    op.drop_index(op.f('ix_provider_health_provider_name'), table_name='provider_health')
    op.drop_table('provider_health')
    # ### end Alembic commands ###
