"""Add message analyzer models

Revision ID: ab4351214ceb
Revises: be16e4d5900b
Create Date: 2026-07-18 20:57:40.745673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4351214ceb'
down_revision: Union[str, Sequence[str], None] = 'be16e4d5900b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('receiver', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('scam_type', sa.String(), nullable=True),
    sa.Column('social_engineering_score', sa.Integer(), nullable=True),
    sa.Column('ocr_confidence', sa.Integer(), nullable=True),
    sa.Column('threat_intel_confidence', sa.Integer(), nullable=True),
    sa.Column('language_confidence', sa.Integer(), nullable=True),
    sa.Column('reputation_confidence', sa.Integer(), nullable=True),
    sa.Column('rule_engine_confidence', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_scans_id'), 'message_scans', ['id'], unique=False)
    op.create_index(op.f('ix_message_scans_platform'), 'message_scans', ['platform'], unique=False)
    op.create_table('message_iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('ioc_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['message_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_iocs_id'), 'message_iocs', ['id'], unique=False)
    op.create_table('message_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('reputation', sa.String(), nullable=True),
    sa.Column('scam_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['message_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_phones_id'), 'message_phones', ['id'], unique=False)
    op.create_table('message_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('redirect_chain', sa.JSON(), nullable=True),
    sa.Column('provider_results', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['message_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_urls_id'), 'message_urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_urls_id'), table_name='message_urls')
    op.drop_table('message_urls')
    op.drop_index(op.f('ix_message_phones_id'), table_name='message_phones')
    op.drop_table('message_phones')
    op.drop_index(op.f('ix_message_iocs_id'), table_name='message_iocs')
    op.drop_table('message_iocs')
    op.drop_index(op.f('ix_message_scans_platform'), table_name='message_scans')
    op.drop_index(op.f('ix_message_scans_id'), table_name='message_scans')
    op.drop_table('message_scans')
    # ### end Alembic commands ###
