"""Add EmailScan models

Revision ID: be16e4d5900b
Revises: 708fa9842d9f
Create Date: 2026-07-18 20:01:04.177918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be16e4d5900b'
down_revision: Union[str, Sequence[str], None] = '708fa9842d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sender_address', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('reply_to', sa.String(), nullable=True),
    sa.Column('return_path', sa.String(), nullable=True),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('spf_status', sa.String(), nullable=True),
    sa.Column('dkim_status', sa.String(), nullable=True),
    sa.Column('dmarc_status', sa.String(), nullable=True),
    sa.Column('sender_reputation', sa.String(), nullable=True),
    sa.Column('domain_age', sa.Integer(), nullable=True),
    sa.Column('is_disposable', sa.Boolean(), nullable=True),
    sa.Column('is_scam_domain', sa.Boolean(), nullable=True),
    sa.Column('brand_impersonation_target', sa.String(), nullable=True),
    sa.Column('social_engineering_score', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_scans_id'), 'email_scans', ['id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('extension', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('dangerous_extension', sa.Boolean(), nullable=True),
    sa.Column('double_extension', sa.Boolean(), nullable=True),
    sa.Column('is_executable', sa.Boolean(), nullable=True),
    sa.Column('has_macro', sa.Boolean(), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=True),
    sa.Column('is_password_protected', sa.Boolean(), nullable=True),
    sa.Column('vt_detection_ratio', sa.String(), nullable=True),
    sa.Column('vt_first_seen', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_id'), 'email_attachments', ['id'], unique=False)
    op.create_table('email_hops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_hops_id'), 'email_hops', ['id'], unique=False)
    op.create_table('email_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('final_redirect', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('threat_category', sa.String(), nullable=True),
    sa.Column('vt_verdict', sa.String(), nullable=True),
    sa.Column('gsb_verdict', sa.String(), nullable=True),
    sa.Column('urlscan_verdict', sa.String(), nullable=True),
    sa.Column('ssl_status', sa.String(), nullable=True),
    sa.Column('domain_age', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['email_scans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_urls_id'), 'email_urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_urls_id'), table_name='email_urls')
    op.drop_table('email_urls')
    op.drop_index(op.f('ix_email_hops_id'), table_name='email_hops')
    op.drop_table('email_hops')
    op.drop_index(op.f('ix_email_attachments_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index(op.f('ix_email_scans_id'), table_name='email_scans')
    op.drop_table('email_scans')
    # ### end Alembic commands ###
